gostudent_dbt:  
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: postgres
      dbname: gostudent  
      schema: "dev_{{ env_var('USER', 'unknown') | lower | replace('_', '') }}"  # Dynamic schema for dev
    prod:
      type: postgres
      threads: 1
      host: localhost  
      port: 5432
      user: postgres
      pass: postgres
      dbname: gostudent  
      schema: "prod_{{ env_var('USER', 'unknown') | lower | replace('_', '') }}" # Dynamic schema for prod
  target: dev  # Default target for dbt
